In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import keras
import tensorflow as tf

In [18]:
a=tf.constant([-4,-3,-2,-1,0,1,2,3,4],dtype=tf.float32)
b=keras.activations.sigmoid(a)
b.numpy()

array([0.01798621, 0.04742587, 0.11920292, 0.26894143, 0.5       ,
       0.7310586 , 0.880797  , 0.95257413, 0.98201376], dtype=float32)

In [19]:
a=tf.constant([-4,-3,-2,-1,0,1,2,3,4],dtype=tf.float32)
b=keras.activations.relu(a)
b.numpy()

array([0., 0., 0., 0., 0., 1., 2., 3., 4.], dtype=float32)

In [20]:
a=tf.constant([-4,-3,-2,-1,0,1,2,3,4],dtype=tf.float32)
b=keras.activations.selu(a)
b.numpy()

array([-1.7258987, -1.6705688, -1.5201665, -1.1113307,  0.       ,
        1.050701 ,  2.101402 ,  3.152103 ,  4.202804 ], dtype=float32)

In [21]:
a=tf.constant([-4,-3,-2,-1,0,1,2,3,4],dtype=tf.float32)
b=keras.activations.elu(a)
b.numpy()

array([-0.9816844 , -0.95021296, -0.86466473, -0.63212055,  0.        ,
        1.        ,  2.        ,  3.        ,  4.        ], dtype=float32)

In [30]:
a=tf.constant([-4,-3,-2,-1,0,1,2,3,4],dtype=tf.float32)
b=keras.activations.tanh(a)
b.numpy()

array([-0.9993292, -0.9950547, -0.9640276, -0.7615942,  0.       ,
        0.7615942,  0.9640276,  0.9950547,  0.9993292], dtype=float32)

In [53]:
a=tf.constant([[-2,-1,0,1,2]],dtype=tf.float32)
b=keras.activations.softmax(a,axis=1)
b.numpy()

array([[0.01165623, 0.03168492, 0.08612854, 0.23412165, 0.6364086 ]],
      dtype=float32)

In [55]:
a=tf.constant([[-2,-1,0,1,2]],dtype=tf.float32)
b=keras.activations.softplus(a)
b.numpy()

array([[0.12692805, 0.31326163, 0.6931472 , 1.3132616 , 2.126928  ]],
      dtype=float32)

In [56]:
a=tf.constant([[-2,-1,0,1,2]],dtype=tf.float32)
b=keras.activations.softsign(a)
b.numpy()

array([[-0.6666667, -0.5      ,  0.       ,  0.5      ,  0.6666667]],
      dtype=float32)

In [58]:
a=tf.constant([[-2,-1,0,1,2]],dtype=tf.float32)
b=keras.activations.exponential(a)
b.numpy()

array([[0.13533528, 0.36787945, 1.        , 2.7182817 , 7.389056  ]],
      dtype=float32)

In [60]:
a=tf.constant([[-2,-1,0,1,2]],dtype=tf.float32)
b=keras.activations.linear(a)
b.numpy()

array([[-2., -1.,  0.,  1.,  2.]], dtype=float32)